const char* MOBY_DICK_OR_THE_WHALE =

"CHAPTER 3\n"
"\n"
"The Spouter-Inn.\n"
"\n"
"\n"
"Entering that gable-ended Spouter-Inn, you found yourself in a wide,\n"
"low, straggling entry with old-fashioned wainscots, reminding one of\n"
"the bulwarks of some condemned old craft.  On one side hung a very\n"
"large oilpainting so thoroughly besmoked, and every way defaced,\n"
"that in the unequal crosslights by which you viewed it, it was only\n"
"by diligent study and a series of systematic visits to it, and\n"
"careful inquiry of the neighbors, that you could any way arrive at an\n"
"understanding of its purpose.  Such unaccountable masses of shades\n"
"and shadows, that at first you almost thought some ambitious young\n"
"artist, in the time of the New England hags, had endeavored to\n"
"delineate chaos bewitched.  But by dint of much and earnest\n"
"contemplation, and oft repeated ponderings, and especially by\n"
"throwing open the little window towards the back of the entry, you at\n"
"last come to the conclusion that such an idea, however wild, might\n"
"not be altogether unwarranted.\n"
"\n"
"But what most puzzled and confounded you was a long, limber,\n"
"portentous, black mass of something hovering in the centre of the\n"
"picture over three blue, dim, perpendicular lines floating in a\n"
"nameless yeast.  A boggy, soggy, squitchy picture truly, enough to\n"
"drive a nervous man distracted.  Yet was there a sort of indefinite,\n"
"half-attained, unimaginable sublimity about it that fairly froze you\n"
"to it, till you involuntarily took an oath with yourself to find out\n"
"what that marvellous painting meant.  Ever and anon a bright, but,\n"
"alas, deceptive idea would dart you through.--It's the Black Sea in a\n"
"midnight gale.--It's the unnatural combat of the four primal\n"
"elements.--It's a blasted heath.--It's a Hyperborean winter\n"
"scene.--It's the breaking-up of the icebound stream of Time.  But at\n"
"last all these fancies yielded to that one portentous something in\n"
"the picture's midst.  THAT once found out, and all the rest were\n"
"plain.  But stop; does it not bear a faint resemblance to a gigantic\n"
"fish? even the great leviathan himself?\n"
"\n"
"In fact, the artist's design seemed this: a final theory of my own,\n"
"partly based upon the aggregated opinions of many aged persons with\n"
"whom I conversed upon the subject.  The picture represents a\n"
"Cape-Horner in a great hurricane; the half-foundered ship weltering\n"
"there with its three dismantled masts alone visible; and an\n"
"exasperated whale, purposing to spring clean over the craft, is in\n"
"the enormous act of impaling himself upon the three mast-heads.\n"
"\n"
"The opposite wall of this entry was hung all over with a heathenish\n"
"array of monstrous clubs and spears.  Some were thickly set with\n"
"glittering teeth resembling ivory saws; others were tufted with knots\n"
"of human hair; and one was sickle-shaped, with a vast handle sweeping\n"
"round like the segment made in the new-mown grass by a long-armed\n"
"mower.  You shuddered as you gazed, and wondered what monstrous\n"
"cannibal and savage could ever have gone a death-harvesting with such\n"
"a hacking, horrifying implement.  Mixed with these were rusty old\n"
"whaling lances and harpoons all broken and deformed.  Some were\n"
"storied weapons.  With this once long lance, now wildly elbowed,\n"
"fifty years ago did Nathan Swain kill fifteen whales between a\n"
"sunrise and a sunset.  And that harpoon--so like a corkscrew now--was\n"
"flung in Javan seas, and run away with by a whale, years afterwards\n"
"slain off the Cape of Blanco.  The original iron entered nigh the\n"
"tail, and, like a restless needle sojourning in the body of a man,\n"
"travelled full forty feet, and at last was found imbedded in the\n"
"hump.\n"
"\n"
;
